name: c-build

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: make C program
        working-directory: build
        run: gcc -o add add.c

      - name: Run a one-line script
        working-directory: build
        run: |
            docker build -t ghcr.io/skiyl9x/add_c_app:$GITHUB_RUN_ID -f Dockerfile .

      - name: Login to GH Packages
        run: |
            echo ${{ secrets.GH_PACKAGES_TOKEN }} | docker login ghcr.io -u skiyl9x --password-stdin

      - name: Run a multi-line script
        run: |
            docker push ghcr.io/skiyl9x/add_c_app:$GITHUB_RUN_ID