name: c-build

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: make C program
        working-directory: build
        run: gcc -o add add.c

      - name: Run a one-line script
        working-directory: build
        run: docker build -t ghcr.io/skiyl9x/_add_c_app:rh8_v3 -f Dockerfile .

      - name: Run a multi-line script
        run: docker push ghcr.io/skiyl9x/_add_c_app:rh8_v3