name: c-build

on:
  push:
    branches: [ "dev" ]
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: add_c_app:$GITHUB_RUN_ID

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: make C program
        working-directory: build
        run: gcc -o add add.c

        # - name: Run a one-line script
        # working-directory: build
        #run: |
        #    docker build -t ghcr.io/skiyl9x/add_c_app:$GITHUB_RUN_ID -f Dockerfile .

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@v4
#         with:
#           images: ${{ inputs.registry }}/${{ inputs.image }}
          
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v3
#         with:
#           context: ${{ inputs.context }}
#           push: ${{ inputs.push }}
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #- name: Run a multi-line script
          #run: |
          # docker push ghcr.io/skiyl9x/add_c_app:$GITHUB_RUN_ID
