name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  deployToTesting:
    runs-on: RedHat8
    environment: production
    steps:
      - 
       name: copy certs
       run: |
            echo "${{ secrets.DOCKER_CA_PEM }}" > ca.pem
            echo "${{ secrets.DOCKER_CLIENT_CERT_PEM }}" > cert.pem 
            echo "${{ secrets.DOCKER_CLIENT_KEY_PEM }}" > key.pem
      - 
        name: check docker connection
        run: |
            docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=35.240.69.15:2375 version